### PR TITLE
Made changes in the setup.sh for file name conversion task

### PR DESCRIPTION
**Pull request by krsharma19**
@awagle Kindly review the changes I have made in the setup.sh script.

### CODE REVIEW

**Comment by krsharma19** [comment]
Updating dockerfile by changing base OS from debian:jessie-slim to debian:stretch-slim

**Comment by awagle** [comment]
What's commit 4bbb2c7 for?

**Comment by krsharma19** [comment]
That is for renaming the substvar file from pcf.substvar to bw.substvar. I
created this pull request earlier for the file renaming thing and the new
pull request also got added to the older one as it wasn't merged earlier.

**Comment by krsharma19** [comment]
Creating a new pull request for the substvar file renaming task and hence, closing this pull request.

**Pull request closed without merging**
